name: mood_note_client

description: "毕业设计"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_quill: ^11.5.0
  record: ^6.1.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 宋体
      fonts:
        - asset: assets/fonts/宋体.ttf

    - family: 楷体
      fonts:
        - asset: assets/fonts/楷体.ttf

    - family: 手写体
      fonts:
        - asset: assets/fonts/手写体.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/weather/
    - assets/images/mood/
    - assets/images/event/

# --- 启动屏配置 ---
flutter_native_splash:
  #背景颜色 (推荐白色，符合心晴记的简约风)
  color: "#FFFFFF"
  #中间的 Logo 图片路径
  image: assets/images/start-logo.png
  #针对 Android 12+ (API 31以上) 的特殊适配
  # 你的 Pixel 8 模拟器是 API 35，这一步至关重要！
  android_12:
    image: assets/images/start-logo.png
    color: "#FFFFFF"
    branding: assets/images/start-branding.png
  #是否全屏显示 (隐藏状态栏)
  fullscreen: false

# --- 应用图标配置 ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  #指定你的图标路径
  image_path: "assets/images/logo.png"
  #移除 alpha 通道（防止 iOS 审核因为透明度报错，这里设为 false 即可）
  remove_alpha_ios: true
  # --- Android 适配核心配置 ---
  # 背景颜色：白色
  adaptive_icon_background: "#FFFFFF"
  # 前景图片：使用同一张带白边的图
  adaptive_icon_foreground: "assets/images/logo.png"
